// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: book.proto

package testproto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Book is the test resource for the fieldbehavior and fieldmask packages.
// Its fields cover every field behavior and shape the packages care about:
// identifier, required, output-only, input-only, immutable, nested message,
// map, and repeated fields.
type Book struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the book.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The title of the book.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// The author of the book.
	Author *Author `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	// The ISBN assigned when the book is first registered.
	Isbn string `protobuf:"bytes,4,opt,name=isbn,proto3" json:"isbn,omitempty"`
	// When the book was created.
	CreateTime string `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Import credentials, accepted on input and never returned.
	ImportToken string `protobuf:"bytes,6,opt,name=import_token,json=importToken,proto3" json:"import_token,omitempty"`
	// Free-form labels.
	Labels map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Shelves the book appears on.
	Shelves []string `protobuf:"bytes,8,rep,name=shelves,proto3" json:"shelves,omitempty"`
	// Reviews of the book, keyed by reviewer.
	Reviews map[string]*Review `protobuf:"bytes,9,rep,name=reviews,proto3" json:"reviews,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Number of pages.
	PageCount int32 `protobuf:"varint,10,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	// Edition names keyed by edition number.
	Editions map[int32]string `protobuf:"bytes,11,rep,name=editions,proto3" json:"editions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Reviews shown on the book's landing page.
	FeaturedReviews []*Review `protobuf:"bytes,12,rep,name=featured_reviews,json=featuredReviews,proto3" json:"featured_reviews,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_book_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Book) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *Book) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Book) GetImportToken() string {
	if x != nil {
		return x.ImportToken
	}
	return ""
}

func (x *Book) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Book) GetShelves() []string {
	if x != nil {
		return x.Shelves
	}
	return nil
}

func (x *Book) GetReviews() map[string]*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

func (x *Book) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *Book) GetEditions() map[int32]string {
	if x != nil {
		return x.Editions
	}
	return nil
}

func (x *Book) GetFeaturedReviews() []*Review {
	if x != nil {
		return x.FeaturedReviews
	}
	return nil
}

// Author of a book.
type Author struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The author's display name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The author's age.
	Age int32 `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	// Whether the author's identity is verified.
	Verified      bool `protobuf:"varint,3,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_book_proto_rawDescGZIP(), []int{1}
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Author) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Author) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

// Review of a book.
type Review struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The review text.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// The star rating, 1 to 5.
	Rating        int32 `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_book_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_book_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_book_proto_rawDescGZIP(), []int{2}
}

func (x *Review) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

// CreateBookRequest exercises request-level required fields.
type CreateBookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent shelf.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The book to create.
	Book          *Book `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookRequest) Reset() {
	*x = CreateBookRequest{}
	mi := &file_book_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookRequest) ProtoMessage() {}

func (x *CreateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookRequest.ProtoReflect.Descriptor instead.
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return file_book_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBookRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateBookRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

var File_book_proto protoreflect.FileDescriptor

const file_book_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"book.proto\x12\ttestproto\x1a\x1fgoogle/api/field_behavior.proto\"\xd5\x05\n" +
	"\x04Book\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tB\x03\xe0A\x02R\x05title\x12.\n" +
	"\x06author\x18\x03 \x01(\v2\x11.testproto.AuthorB\x03\xe0A\x01R\x06author\x12\x17\n" +
	"\x04isbn\x18\x04 \x01(\tB\x03\xe0A\x05R\x04isbn\x12$\n" +
	"\vcreate_time\x18\x05 \x01(\tB\x03\xe0A\x03R\n" +
	"createTime\x12&\n" +
	"\fimport_token\x18\x06 \x01(\tB\x03\xe0A\x04R\vimportToken\x128\n" +
	"\x06labels\x18\a \x03(\v2\x1b.testproto.Book.LabelsEntryB\x03\xe0A\x01R\x06labels\x12\x1d\n" +
	"\ashelves\x18\b \x03(\tB\x03\xe0A\x01R\ashelves\x12;\n" +
	"\areviews\x18\t \x03(\v2\x1c.testproto.Book.ReviewsEntryB\x03\xe0A\x01R\areviews\x12\"\n" +
	"\n" +
	"page_count\x18\n" +
	" \x01(\x05B\x03\xe0A\x01R\tpageCount\x12>\n" +
	"\beditions\x18\v \x03(\v2\x1d.testproto.Book.EditionsEntryB\x03\xe0A\x01R\beditions\x12A\n" +
	"\x10featured_reviews\x18\f \x03(\v2\x11.testproto.ReviewB\x03\xe0A\x01R\x0ffeaturedReviews\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aM\n" +
	"\fReviewsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.testproto.ReviewR\x05value:\x028\x01\x1a;\n" +
	"\rEditionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\x06Author\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12\x15\n" +
	"\x03age\x18\x02 \x01(\x05B\x03\xe0A\x01R\x03age\x12\x1f\n" +
	"\bverified\x18\x03 \x01(\bB\x03\xe0A\x03R\bverified\">\n" +
	"\x06Review\x12\x17\n" +
	"\x04text\x18\x01 \x01(\tB\x03\xe0A\x02R\x04text\x12\x1b\n" +
	"\x06rating\x18\x02 \x01(\x05B\x03\xe0A\x01R\x06rating\"Z\n" +
	"\x11CreateBookRequest\x12\x1b\n" +
	"\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02R\x06parent\x12(\n" +
	"\x04book\x18\x02 \x01(\v2\x0f.testproto.BookB\x03\xe0A\x02R\x04bookB6Z4github.com/AndreiCocan/golang-aip/internal/testprotob\x06proto3"

var (
	file_book_proto_rawDescOnce sync.Once
	file_book_proto_rawDescData []byte
)

func file_book_proto_rawDescGZIP() []byte {
	file_book_proto_rawDescOnce.Do(func() {
		file_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_book_proto_rawDesc), len(file_book_proto_rawDesc)))
	})
	return file_book_proto_rawDescData
}

var file_book_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_book_proto_goTypes = []any{
	(*Book)(nil),              // 0: testproto.Book
	(*Author)(nil),            // 1: testproto.Author
	(*Review)(nil),            // 2: testproto.Review
	(*CreateBookRequest)(nil), // 3: testproto.CreateBookRequest
	nil,                       // 4: testproto.Book.LabelsEntry
	nil,                       // 5: testproto.Book.ReviewsEntry
	nil,                       // 6: testproto.Book.EditionsEntry
}
var file_book_proto_depIdxs = []int32{
	1, // 0: testproto.Book.author:type_name -> testproto.Author
	4, // 1: testproto.Book.labels:type_name -> testproto.Book.LabelsEntry
	5, // 2: testproto.Book.reviews:type_name -> testproto.Book.ReviewsEntry
	6, // 3: testproto.Book.editions:type_name -> testproto.Book.EditionsEntry
	2, // 4: testproto.Book.featured_reviews:type_name -> testproto.Review
	0, // 5: testproto.CreateBookRequest.book:type_name -> testproto.Book
	2, // 6: testproto.Book.ReviewsEntry.value:type_name -> testproto.Review
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_book_proto_init() }
func file_book_proto_init() {
	if File_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_proto_rawDesc), len(file_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_book_proto_goTypes,
		DependencyIndexes: file_book_proto_depIdxs,
		MessageInfos:      file_book_proto_msgTypes,
	}.Build()
	File_book_proto = out.File
	file_book_proto_goTypes = nil
	file_book_proto_depIdxs = nil
}
